import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { TonConnectUIProvider } from "@tonconnect/ui-react";
import { Toaster } from "sonner";
import App from "@/App";
import "@/lib/i18n";
import "@/index.css";
const manifestUrl = import.meta.env.VITE_TON_MANIFEST_URL ?? "http://localhost:5173/tonconnect-manifest.json";
createRoot(document.getElementById("root")).render(_jsx(StrictMode, { children: _jsxs(TonConnectUIProvider, { manifestUrl: manifestUrl, children: [_jsx(App, {}), _jsx(Toaster, { richColors: true, position: "top-center" })] }) }));
