import { jsx as _jsx } from "react/jsx-runtime";
import * as React from "react";
import { cn } from "@/lib/utils";
const Card = React.forwardRef(({ className, ...props }, ref) => (_jsx("div", { ref: ref, className: cn("rounded-2xl border border-border/60 bg-card/80 text-card-foreground shadow-lg backdrop-blur-sm", className), ...props })));
Card.displayName = "Card";
const CardHeader = React.forwardRef(({ className, ...props }, ref) => _jsx("div", { ref: ref, className: cn("flex flex-col space-y-1.5 p-4", className), ...props }));
CardHeader.displayName = "CardHeader";
const CardTitle = React.forwardRef(({ className, ...props }, ref) => _jsx("h3", { ref: ref, className: cn("text-base font-bold leading-none", className), ...props }));
CardTitle.displayName = "CardTitle";
const CardContent = React.forwardRef(({ className, ...props }, ref) => _jsx("div", { ref: ref, className: cn("p-4 pt-0", className), ...props }));
CardContent.displayName = "CardContent";
export { Card, CardHeader, CardTitle, CardContent };
